### ISSUE TITLE
feature request: alternative "forced" initialization

### ISSUE THREAD

**Issue by wdkrnls** [francescopantalone/Spbsampling#1]
Hi,

I saw your article in JSS and noticed you only include one initialization scheme in your PWD: choosing one point among your candidate set uniformly at random. In the Greenfield large sampling case, I can see how that would be fine. However, in many existing applications there are pre-existing points with which you are going to get data for anyway (even if they are not optimal)  and I would like to account for them in the probability of inclusion updating scheme so that analyses which include both data sets in their analysis remain maximally spatially balanced. Could this package be extended to cover this use case?

**Comment by wdkrnls** [comment]
This might be handled by adding an argument which excludes indexed items from being swapped out along with another argument specifying the initially selected items. With both of these arguments in place you just need one more argument to specify the desired overlap rate to aim for as that should get you to your controlled positive coordination with the previous sample situation you discussed in the JSS article. Might be even nicer if you optionally left it up to the user to supply a function for specifying the acceptance criterion for each subsequent sample in terms of either the previous sample or the first sample.

**Comment by francescopantalone** [comment]
Hi,

thanks for this, and sorry for my very late reply.

Actually, we have been working on this very case - I hope I can give you some updates soon.

Thanks!

**Comment by francescopantalone** [comment]
Hi,

thanks for this, and sorry for my very late reply.

Actually, we have been working on this very case - I hope I can give you some updates soon.

I'll close this and reopen when needed.

Thanks!

**Comment by francescopantalone** [comment]
Hi,

thanks for this, and sorry for my very late reply.

Actually, we have been working on this very case - I hope I can update the package soon.

I'll close this and reopen when needed.

Thanks!
